### ISSUE TITLE
Android Gradle Plugin 1.3.0 + Retrolambda breaks compilation of tests

### ISSUE THREAD

**Issue by artem-zinnatullin** [evant/gradle-retrolambda#120]
Hello, we've updated Android Gradle Plugin to 1.3.0 (didn't touch anything but this) and now tests with Robolectric does not compile with following error:

```
:app:compileRetrolambdaRobolectricDebug
:app:preRobolectricDebugUnitTestBuild UP-TO-DATE
:app:prepareRobolectricDebugUnitTestDependencies
:app:processRobolectricDebugUnitTestJavaRes
:app:compileRobolectricDebugUnitTestJavaWithJavac
An exception has occurred in the compiler (1.8.0_45). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
:app:compileRobolectricDebugUnitTestJavaWithJavac FAILED
```

`robolectric` is flavor with robolectric tests.

Looks like it's related to #23.

I can file an issue on b.android.com if it's problem of Android Gradle Plugin.

**Comment by ZeroBrain** [comment]
It was occurred with Robolectric 3.0.

**Comment by tomrozb** [comment]
I've got the same problem. It occurs only on one computer, on another two it compiles without problems. In fact it works from command line but fails when building from studio.

```
:lib-android:processReleaseManifest UP-TO-DATE
:lib-android:processReleaseResources UP-TO-DATE
:lib-android:generateReleaseSources
:lib-android:processReleaseJavaRes UP-TO-DATE
:lib-android:compileReleaseJavaWithJavac
An exception has occurred in the compiler (1.8.0_51). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
Error:Execution failed for task ':lib-android:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by evant** [comment]
@tomrozb Interesting, if you say it builds from the command line but fails from studio, have you tried going into the test run configuration and replacing "Make" with "Gradle aware Make"?

**Comment by artem-zinnatullin** [comment]
I have problems with building from the terminal.

**Comment by tomrozb** [comment]
@evant Yes, I know very well about this setting but it doesn't change anything.

**Comment by ZeroBrain** [comment]
@evant  If I use Robolectric 2.4, I can build but Robolectric 3.0

**Comment by ChrisZou** [comment]
I run into the same error after upgrading android gradle plugin from 1.2.3 to 1.3.0, can't run robolectric test from the terminal.

**Comment by neworld** [comment]
I created empty project only with retrolambda and android gradle plugin 1.3.0. Tests do not compile. But they compile with 1.2.3 plugin version, without retrolamba or by removing lambdas from source.

Repo for easy testing: https://github.com/neworld/retrolambda-android-gradle-1.3.0

**Comment by evant** [comment]
Looks like it's because `compileDebugUnitTestJava` was renamed to `compileDebugUnitTestJavaWithJavac`. I wonder if there is a better way to get at that task than the name.

**Comment by artem-zinnatullin** [comment]
You can ask Android Developer Tools team https://groups.google.com/forum/#!forum/adt-dev

**Comment by ZeroBrain** [comment]
@evant oh thx god.

**Comment by rickytribbia** [comment]
Sorry, but I encountered this bug again with this setup: 

**project level build.gradle file:**

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'me.tatarka:gradle-retrolambda:3.2.2'
        classpath 'com.caverock:androidsvg:1.2.1'
    }
}
allprojects {
    repositories {
        mavenCentral()
    }
}
```
**app module level build.gradle file:**
```
apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'

android {
    compileSdkVersion 22
    buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 22
        multiDexEnabled true
    }

    lintOptions {
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

retrolambda {
    jdk System.getenv("JAVA8_HOME")
    oldJdk System.getenv("JAVA7_HOME")
    javaVersion JavaVersion.VERSION_1_7
    jvmArgs '-arg1', '-arg2'
    defaultMethods false
    incremental true
}
```
**env variables:**
```
$JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
$JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home
$JAVA7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
```
**gradle-wrapper.properties**
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-1.12-all.zip
```
**Error occurred:**
```
:app:compileDebugJavaWithJavac
An exception has occurred in the compiler (1.8.0_51). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
**Execution of command:**
```
gradle app:compileDebugJavaWithJavac --info
```
results: 
```
Starting Build
Settings evaluated using settings file '*<projectfolder>*/settings.gradle'.
Projects loaded. Root project using build file '*<projectfolder>*/build.gradle'.
Included projects: [root project '*<projectname>*', project ':app', project ':*<other_module>*', project ':*<other_module2>*']
Evaluating root project '*<projectnamer>*' using build file '*<projectfolder>*/build.gradle'.
Evaluating project ':app' using build file '*<projectfolder>*/app/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/*<projectfolder>*/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not create plugin of type 'AppPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 3.253 secs
```

**Comment by ZeroBrain** [comment]
@rickytribbia

### gradle.properties

```distributionUrl=https\://services.gradle.org/distributions/gradle-1.12-all.zip```
to 
```distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip```

**Comment by rickytribbia** [comment]
Thanks for your answer. 

I have tried to change as you said, but it doesn't change the error. I have made the suggested edit in my "gradle-wrapper.properties" file and not in "gradle.properties" file as you suggest. In this project i haven't "gradle.properties" file. 

```
#Sun Mar 01 16:02:38 CET 2015
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip
```

I check also my GRADLE_USER_HOME env variable and I see: 
```
~/.gradle/wrapper/dists/gradle-2.1-all/488seql5pimt7vjvdsuqhh1ut/gradle-2.1
```
so I also tried: 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip
```

Looking into ```~/.gradle/wrapper/dists/``` folder I see
![gradle_wrapper_dists_subfolders](http://s18.postimg.org/un623hxw9/gradle_wrapper_dist_subfolders.png)

**Comment by rickytribbia** [comment]
I found my solution. 

As said by @stepango at #61 I change my app.gradle file: 

```
String java8 = getJavaVersion(8)
String java7 = getJavaVersion(7)

retrolambda {
    jdk java8
    oldJdk java7
    javaVersion JavaVersion.VERSION_1_7
//    jvmArgs '-arg1', '-arg2' < if I don't comment this line gradle fails
    defaultMethods false
    incremental true
}

String getJavaVersion(Integer v) {
    def sout = new StringBuffer()
    def proc = "/usr/libexec/java_home -v 1.$v".execute()
    proc.consumeProcessOutput(sout, new StringBuffer())
    proc.waitForOrKill(1000)
    return sout.toString().replace("\n", "").replace("\r", "")
}
```
Thanks again @ZeroBrain for the support.
