### ISSUE TITLE
Robolectric-shadow-based unit tests are failing on 2.3.0

### ISSUE THREAD

**Issue by budnyjj** [evant/gradle-retrolambda#213]
I'm trying to executAfter update from 2.2.5 to 2.3.0 I'm getting the following error during execution of unit tests, which use Robolectric's shadows:
```java
**.SomeTest > **Test FAILED
    java.lang.NoClassDefFoundError: **.SomeClass

        Caused by:
        java.lang.ClassNotFoundException: couldn't load **.SomeClass

            Caused by:
            java.lang.ClassCastException: org.objectweb.asm.tree.InvokeDynamicInsnNode cannot be cast to org.objectweb.asm.tree.MethodInsnNode
```
