### ISSUE TITLE
NoClassDefFoundError sometimes

### ISSUE THREAD

**Issue by evant** [evant/gradle-retrolambda#60]
Issue from https://github.com/orfjackal/retrolambda/issues/37

**Comment by Diolor** [comment]
Here is a assumption why this fails (still the reproduction is random here). The `compileFlavorBuildJava` happens before the `compileRetrolambdaFlavorBuild`.

```
:mobile:compileDevelopDebugJava
:mobile:_compileDevelopDebugJava
:mobile:compileRetrolambdaDevelopDebug
```

If I turn proguard "on" then assuming the build is affected by this bug the `:mobile:compileDevelopDebugJava` will fail without this plugin had the chance to build the lambdas and make the conversions.

PS: gradle:1.1.3

**Comment by ypresto** [comment]
For workaround after it happens, `rm -rf ./app/build/intermediates/classes` and assembleFlavorBuild will fix the error.

**Comment by ypresto** [comment]
It does not happen when `incremental false`.

**Comment by vkotovv** [comment]
I'm still seeing this after bumping plugin version to 3.2.3 and cleaning my project. Tried manually deleting *build/* folder. What can be the case?

**Comment by paulirotta** [comment]
I get good results for months by adding
     classpath 'me.tatarka.retrolambda.projectlombok:lombok.ast:0.2.3.a2'
but still see the lint issue without this.

Is there a reason that fix isn't yet merged back into the canonical branch?

**Comment by orrc** [comment]
The fix for this bug was merged directly to the master branch and was released in 3.2.2.

I upgraded to that version of the plugin and removed the `incremental false` workaround mentioned above — I haven't experienced this bug since then.

Nobody else has mentioned Lint here — are you talking about a different issue to this one, which relates to `NoClassDefFoundError`s?
