### ISSUE TITLE
Compilation error on multi-flavor project

### ISSUE THREAD

**Issue by lgawin** [evant/gradle-retrolambda#210]
In case of multi-flavor project, when test code contains lambda, build fails with `3.3.0` version of plugin. 

To be precise, gradle task `transformClassesWithRetrolambdaFor{Flavor}DebugAndroidTest` fails with
```
Execution failed for task ':sample-android-app:transformClassesWithRetrolambdaForFreeDebugAndroidTest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

And detailed information indicates `java.lang.ClassNotFoundException`.

It works well with `3.2.5`

**Comment by lgawin** [comment]
Very similar to #194

It can be easily reproduced using `sample-android-app` by adding flavors, e.g.
```
productFlavors {
    free {}
    paid {}
}
```
Then execution of `./gradlew connectedAndroidTest` fails with log

```
Saving lambda class: me/tatarka/sample/app/test/MainActivityInstrumentationTest$$Lambda$1
Error! Failed to run Retrolambda
java.lang.RuntimeException: Failed to backport class: me/tatarka/sample/app/test/MainActivityInstrumentationTest
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:128)
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:107)
        at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:47)
        at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:77)
        at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.RuntimeException: Failed to backport lambda or method reference: me/tatarka/sample/app/test/MainActivityInstrumentationTest.lambda$testWithEspresso$1(Landroid/view/View;Landroid/support/test/espresso/NoMatchingViewException;)V (6)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
        at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:171)
        at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:160)
        at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1452)
        at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
        at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
        at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
        at net.orfjackal.retrolambda.Transformers.lambda$transform$5(Transformers.java:107)
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:124)
        ... 4 more
Caused by: java.lang.TypeNotPresentException: Type android.support.test.espresso.ViewAssertion not present
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:63)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
        at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
        at net.orfjackal.retrolambda.lambdas.Types.toMethodType(Types.java:33)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:104)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: android.support.test.espresso.ViewAssertion
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
        ... 18 more
:sample-android-app:transformClassesWithRetrolambdaForFreeDebugAndroidTest FAILED
```

See branch on my fork: https://github.com/lgawin/gradle-retrolambda/tree/issue-%23210-class-not-found-on-3.3.0

**Comment by evant** [comment]
I've released `3.3.1-SNAPSHOT` to the sonatype snapshot repo. Can you test to see if this fixes this issue?

**Comment by JakeWharton** [comment]
Looks good here.

On Sat, Oct 15, 2016 at 4:09 PM Evan Tatarka <notifications@github.com>
wrote:

I've released 3.3.1-SNAPSHOT to the sonatype snapshot repo. Can you test to
see if this fixes this issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/evant/gradle-retrolambda/issues/210#issuecomment-254008061>,
or mute the thread

**Comment by evant** [comment]
Release `3.3.1`, should be fixed.
